# Singular Value Decomposition

Matrix decomposition, also known as matrix factorization, involves describing a given matrix using its constituent elements. Perhaps the most known and widely used matrix decomposition method is the Singular-Value Decomposition, or SVD. All matrices have an SVD, which makes it more stable than other methods, such as the eigendecomposition. As such, it is often used in a wide array of applications including compressing, denoising, and data reduction.

# What is the Singular-Value Decomposition

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore the case for complex numbers.

$$A = U\cdot \Sigma \cdot V^T$$

Where A is the real n x m matrix that we wish to decompose, U is an m x m matrix, $\Sigma$ represented by the uppercase Greek letter sigma) is an m x n diagonal matrix, and $V^T$ is the V transpose of an n x n matrix where T is a superscript.

The diagonal values in the $\Sigma$ matrix are known as the singular values of the original matrix A. The columns of the U matrix are called the left-singular vectors of A, and the columns of V are called the right-singular vectors of A. The SVD is calculated via iterative numerical methods. We will not go into the details of these methods. Every rectangular matrix has a singular value decomposition, although the resulting matrices may contain complex numbers and the limitations of floating point arithmetic may cause some matrices to fail to decompose neatly.

The SVD is used widely both in the calculation of other matrix operations, such as matrix inverse, but also as a data reduction method in machine learning. SVD can also be used in least squares linear regression, image compression, and denoising data.

## Calculate Singular-Value Decomposition

The SVD can be calculated by calling the **svd()** function. The function takes a matrix and returns the U, $\Sigma$ and $V^T$ elements. The $\Sigma$ diagonal matrix is returned as a vector of singular values. The V matrix is returned in a transposed form, e.g. $V^T$ . The example below defines a 3 x 2 matrix and calculates the singular-value decomposition.

In [1]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd

# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Reconstruct Matrix

The original matrix can be reconstructed from the U, $\Sigma$, and $V^T$ elements. The U, s, and V elements returned from the **svd()** cannot be multiplied directly. The s vector must be converted into a diagonal matrix using the **diag()** function. By default, this function will create a square matrix that is m x m, relative to our original matrix. This causes a problem as the size of the matrices do not fit the rules of matrix multiplication, where the number of columns in a matrix must match the number of rows in the subsequent matrix. After creating the square $\Sigma$ diagonal matrix, the sizes of the matrices are relative to the original n x m matrix that we are decomposing, as follows:

$$U(m x m)\cdot \Sigma(m x m)\cdot V^T(n x n)$$

We can achieve this by creating a new $\Sigma$ matrix of all zero values that is m x n (e.g. more rows) and populate the first n x n part of the matrix with the square diagonal matrix calculated via **diag()**.

In [2]:
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

# factorize
U, s, V = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


The above complication with the $\Sigma$ diagonal only exists with the case where m and n are not equal. The diagonal matrix can be used directly when reconstructing a square matrix, as follows.

In [3]:
# reconstruct square matrix from svd
from numpy import array
from numpy import diag
from scipy.linalg import svd

# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

# factorize
U, s, V = svd(A)

# create n x n Sigma matrix
Sigma = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Pseudoinverse

The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular matrices where the number of rows and columns are not equal. It is also called the Moore-Penrose Inverse after two independent discoverers of the method or the Generalized Inverse.

The pseudoinverse is denoted as $A^+$, where A is the matrix that is being inverted and + is a superscript. The pseudoinverse is calculated using the singular value decomposition of A:

$$ A^+ = V \cdot D^+ \cdot U^T$$

Where $A^+$ is the pseudoinverse, $D^+$ is the pseudoinverse of the diagonal matrix $\Sigma$ and $V^T$ is
the transpose of V. We can get U and V from the SVD operation.

$$ A = U\cdot \Sigma \cdot V^T$$

The D+ can be calculated by creating a diagonal matrix from $\Sigma$, calculating the reciprocal of each non-zero element in $\Sigma$, and taking the transpose if the original matrix was rectangular.

$$\begin{aligned}
\Sigma = \begin{pmatrix}
s_{1,1}\;\; 0 \;\; 0\\
0\;\; s_{2,2} \;\; 0\\
0\;\; 0\;\; s_{3,3}
\end{pmatrix}
\end{aligned}
$$

$$\begin{aligned}
D^+ = \begin{pmatrix}
\frac{1}{s_{1,1}}\;\; 0 \;\; 0\\
0\;\; \frac{1}{s_{2,2}} \;\; 0\\
0\;\; 0\;\; \frac{1}{s_{3,3}}
\end{pmatrix}
\end{aligned}
$$

The pseudoinverse provides one way of solving the linear regression equation, specifically when there are more rows than there are columns, which is often the case. NumPy provides the function **pinv()** for calculating the pseudoinverse of a rectangular matrix. The example below defines a 4 x 2 matrix and calculates the pseudoinverse.

In [1]:
# pseudoinverse
from numpy import array
from numpy.linalg import pinv

# define matrix
A = array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)

# calculate pseudoinverse
B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.42385628e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


We can calculate the pseudoinverse manually via the SVD and compare the results to the **pinv()** function. First we must calculate the SVD. Next we must calculate the reciprocal of each value in the s array. Then the s array can be transformed into a diagonal matrix with an added row of zeros to make it rectangular. Finally, we can calculate the pseudoinverse from the elements. The specific implementation is:

$$ A^+ = V^T \cdot D^T \cdot U^T$$

The full example is listed below.

In [2]:
# pseudoinverse via svd
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag

# define matrix
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)

# factorize
U, s, V = svd(A)

# reciprocals of s
d = 1.0 / s

# create m x n D matrix
D = zeros(A.shape)

# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)

# calculate pseudoinverse
B = V.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.42578328e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## Dimensionality Reduction

A popular application of SVD is for dimensionality reduction. Data with a large number of features, such as more features (columns) than observations (rows) may be reduced to a smaller subset of features that are most relevant to the prediction problem. The result is a matrix with a lower rank that is said to approximate the original matrix. To do this we can perform an SVD operation on the original data and select the top k largest singular values in $\Sigma$. These columns can be selected from $\Sigma$ and the rows selected from $V^T$ . An approximate B of the original vector A can then be reconstructed.

$$ B = U \cdot \Sigma_k \cdot V_k^T$$

In natural language processing, this approach can be used on matrices of word occurrences or word frequencies in documents and is called Latent Semantic Analysis or Latent Semantic Indexing. In practice, we can retain and work with a descriptive subset of the data called T. This is a dense summary of the matrix or a projection.

$$ T = U\cdot\Sigma_k$$

Further, this transform can be calculated and applied to the original matrix A as well as other similar matrices.

$$ T = A\cdot V_k^T$$

The example below demonstrates data reduction with the SVD. First a 3 x 10 matrix is defined, with more columns than rows. The SVD is calculated and only the first two features are selected. The elements are recombined to give an accurate reproduction of the original matrix. Finally the transform is calculated two different ways.

In [3]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)

# factorize
U, s, V = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]

# reconstruct
B = U.dot(Sigma.dot(V))
print(B)

# transform
T = U.dot(Sigma)
print(T)
T = A.dot(V.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


The scikit-learn provides a TruncatedSVD class that implements this capability directly. The TruncatedSVD class can be created in which you must specify the number of desirable features or components to select, e.g. 2. Once created, you can fit the transform (e.g. calculate $V^T_k$ ) by calling the **fit()** function, then apply it to the original matrix by calling the **transform()** function. The result is the transform of A called T above. The example below demonstrates the TruncatedSVD class.

In [4]:
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD

# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)

# create transform
svd = TruncatedSVD(n_components=2)

# fit transform
svd.fit(A)

# apply transform
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
