# NumPy Array Broadcasting

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A
way to overcome this is to duplicate the smaller array so that it has the dimensionality and
size as the larger array. This is called array broadcasting and is available in NumPy when
performing array arithmetic, which can greatly reduce and simplify your code.

## Limitation with Array Arithmetic

For example, an array a can be defined as **[1, 2, 3]** and array b can be
defined as **[1, 2, 3]** and adding together will result in a new array with the values **[2, 4, 6]**.Strictly, arithmetic may only be performed on arrays that have the same dimensions and dimensions with the same size.This means that a one-dimensional array with the length of 10 can only perform arithmetic with another one-dimensional array with the length 10. Thankfully, NumPy provides a built-in workaround to allow arithmetic between arrays with differing sizes.

## Array Broadcasting

Broadcasting is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size. Although the technique was developed for NumPy, it has also been adopted more broadly in other numerical computational libraries, such as Theano, TensorFlow, and Octave Broadcasting solves the problem of arithmetic between arrays of differing shapes by in effect replicating the smaller array along the last mismatched dimension.

NumPy does not actually duplicate the smaller array, instead, it makes memory and computationally effcient use of existing structures in memory that in effect achieve the same result. The concept has also permeated linear algebra notation to simplify the explanation of simple operations.

In the context of deep learning, we also use some less conventional notation. We allow the addition of matrix and a vector, yielding another matrix: **C = A+b**, where **C<sub>ij</sub> = A<sub>ij</sub> + b<sub>j</sub>** . In other words, the vector b is added to each row of the matrix.

## Broadcasting in NumPy

We can make broadcasting concrete by looking at three examples in NumPy. The examples in this section are not exhaustive,

### Scalar and One-Dimensional Array

A single value or scalar can be used in arithmetic with a one-dimensional array. For example, we can imagine a one-dimensional array a with three values [a1, a2, a3] added to a scalar b.

```
a = [a1, a2, a3]

b = [b1, b2, b3]

c = a + b
c = [a1 + b1, a2 + b2, a3 + b3]
```

In [3]:
# Import library
from numpy import array

# define array
a = array([1, 2, 3])
print(a)

# define scalar
b = 2
print(b)

# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


### Scalar and Two-Dimensional Array

A scalar value can be used in arithmetic with a two-dimensional array. For example, we can imagine a two-dimensional array A with 2 rows and 3 columns added to the scalar b.

In [1]:
# Import necessary libraries
from numpy import array

# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)

# define scalar
b = 2
print(b)

# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


### One-Dimensional and Two-Dimensional Arrays

A one-dimensional array can be used in arithmetic with a two-dimensional array. For example, we can imagine a two-dimensional array A with 2 rows and 3 columns added to a one-dimensional array b with 3 values.

In [2]:
# Import necessary libraries
from numpy import array

# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)

# define one-dimensional array
b = array([1, 2, 3])
print(b)

# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


## Limitations of Broadcasting

Broadcasting is a handy shortcut that proves very useful in practice when working with NumPy arrays. That being said, it does not work for all cases, and in fact imposes a strict rule that must be satised for broadcasting to be performed.

Arithmetic, including broadcasting, can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1. The dimensions are considered in reverse order, starting with the trailing dimension; for example, looking at columns before rows in a two-dimensional case.

This make more sense when we consider that NumPy will in effect pad missing dimensions with a size of 1 when comparing arrays. Therefore, the comparison between a two-dimensional array A with 2 rows and 3 columns and a vector b with 3 elements:

```
A.shape = (2 x 3)
b.shape = (3)

In effect, this becomes a comparison between:
    A.shape = (2 x 3)
    b.shape = (1 x 3)

This same notion applies to the comparison between a scalar that is treated as an array with
the required number of dimensions:
    A.shape = (2 x 3)
    b.shape = (1)

This becomes a comparison between:
    A.shape = (2 x 3)
    b.shape = (1 x 1)

When the comparison fails, the broadcast cannot be performed, and an error is raised.
The example below attempts to broadcast a two-element array to a 2 x 3 array. This
comparison is in effect:
    A.shape = (2 x 3)
    b.shape = (1 x 2)

We can see that the last dimensions (columns) do not match and we would expect the
broadcast to fail. The example below demonstrates this in NumPy.
```

In [4]:
# Import necessary libraries
from numpy import array

# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)

# define one-dimensional array
b = array([1, 2])
print(b.shape)

# attempt broadcast
try:
    C = A + b
    print(C)
except Exception as e: 
    print(e)

(2, 3)
(2,)
operands could not be broadcast together with shapes (2,3) (2,) 
