# Combining Arrays

NumPy provides many functions to create new arrays from existing arrays.

### Vertical Stack

Given two or more array you can stack them vertically using the vstack() function.

following is an example for the same:

In [1]:
# Import the required functions
from numpy import array, vstack

# create first array
a1 = array([1,2,3])
print(a1)

# create second array
a2 = array([4,5,6])
print(a2)

# vertical stack
a3 = vstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


### Horizontal Stack
Given two or more array you can stack them horizontally using hstack() function. 

following is an example for the same:

In [2]:
# Import the required functions
from numpy import array, hstack

# create first array
a1 = array([1,2,3])
print(a1)

# create second array
a2 = array([4,5,6])
print(a2)

# vertical stack
a3 = hstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
