# NumPy N-dimensional Array

NumPy is a python library that can be used for scientific and numerical applicaitons and is the tool to use for linear algebra operations.

The **ndarray** is the main data structure in NumPy which abbrivates to N-dimentional array. When working with Numpy, data is simply refered as an array. It's a fixed size array in memory that contains data of the same type, such as int or float. 

Refer the below example to create an NumPy array:

In [2]:
# Import library
from numpy import array

# create array
l = [1.0,2.0,3.0]
a = array(l)

# Display array
print(a)

# Display array shape
print(a.shape)

# Display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


## Functions to Create Array

Let's look at few conventional functions for creating fixed-sized array.

### Empty
The empty() function will create a new array of the specified shape. The argument to the function is an array or tuple that specifies the length of each dimention of the array to create. 

In [5]:
# Import empty function
from numpy import empty

# create an empty array of 3x3
a = empty([3,3])
print(a)

[[1.14285714 2.28571429 0.57142857]
 [2.28571429 4.97142857 1.54285714]
 [0.57142857 1.54285714 0.88571429]]


#### Zeros
The zeros() function will create a new array of the specified size with the contents filled with zero values.

In [6]:
# Import zeros from numpy
from numpy import zeros

# create zero array
a = zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones 
The ones() function will create a new array of the specified size with the contents filled with one values. The argument to the function is an array or tuple that specifies the length of each dimension of the array to create.

In [7]:
# Import ones form numpy
from numpy import ones

# create ones array
a = ones([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
