# Vectors and Vector Arithmetic

Vectors are a foundational element of linear algebra. Vectors are used throughout the 
eld of
machine learning in the description of algorithms and processes such as the target variable (y)
when training an algorithm.

## Defining a Vector

We can represent a vector in Python as a NumPy array. A NumPy array can be created from a list of numbers. For example, below we define a vector with the length of 3 and the integer values 1, 2 and 3.

In [1]:
# create a vector
from numpy import array

# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


## Vector Arithmetic

### Vector Addition

Two vectors of equal length can be added together to create a new third vector. 
```
c = a + b
```

The new vector has the same length as the other two vectors. Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index, for example:
```
c = (a1 + b1, a2 + b2, a3 + b3)
```
We can add vectors directly in Python by adding NumPy arrays.

In [2]:
# vector addition
from numpy import array

# define first vector
a = array([1, 2, 3])
print(a)

# define second vector
b = array([1, 2, 3])
print(b)

# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


### Vector Subtraction

One vector can be subtracted from another vector of equal length to create a new third vector.
```
c = a - b
```

As with addition, the new vector has the same length as the parent vectors and each element
of the new vector is calculated as the subtraction of the elements at the same indices.
```
c = (a1 - b1, a2 - b2, a3 - b3)
```

The NumPy arrays can be directly subtracted in Python.

In [3]:
# vector subtraction
from numpy import array

# define first vector
a = array([1, 2, 3])
print(a)

# define second vector
b = array([0.5, 0.5, 0.5])
print(b)

# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


### Vector Multiplication
Two vectors of equal length can be multiplied together.
```
c = a x b
```

As with addition and subtraction, this operation is performed element-wise to result in a
new vector of the same length.
```
c = (a1 x b1, a2 x b2, a3 x b3)
```

We can perform this operation directly in NumPy.

In [4]:
# vector multiplication
from numpy import array

# define first vector
a = array([1, 2, 3])
print(a)

# define second vector
b = array([1, 2, 3])
print(b)

# multiply vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### Vector Division

Two vectors of equal length can be divided.
```
c = a/b
```

As with other arithmetic operations, this operation is performed element-wise to result in a
new vector of the same length.
```
c = (a1/b1,a2/b2,a3/b3)
```

We can perform this operation directly in NumPy.

In [5]:
# vector division
from numpy import array

# define first vector
a = array([1, 2, 3])
print(a)

# define second vector
b = array([1, 2, 3])
print(b)

# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


### Vector Dot Product

We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar. This is called the dot product, named because of the dot operator used when describing the operation.
```
c = a.b
```

The operation can be used in machine learning to calculate the weighted sum of a vector. The dot product is calculated as follows:
```
c = (a1 x b1 + a2 x b2 + a3 x b3)
```

We can calculate the dot product between two vectors in Python using the dot() function
on a NumPy array.

In [7]:
# vector dot product
from numpy import array

# define first vector
a = array([1, 2, 3])
print(a)

# define second vector
b = array([1, 2, 3])
print(b)

# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


### Vector-Scalar Multiplication

A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. To keep notation simple, we will use lowercase s to represent the scalar value.
```
c = s x v
```

The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.
```
c = (s x v1, s x v2, s x v3)
```

We can perform this operation directly with the NumPy array.

In [ ]:
# vector-scalar multiplication
from numpy import array

# define vector
a = array([1, 2, 3])
print(a)

# define scalar
s = 0.5
print(s)

# multiplication
c = s * a
print(c)