# Types of Matrices

A lot of linear algebra is concerned with operations on vectors and matrices, and there are many different types of matrices. There are a few types of matrices that you may encounter again and again when getting started in linear algebra, particularity the parts of linear algebra relevant to machine learning.

## Square Matrix

A square matrix is a matrix where the number of rows (n) is equivalent to the number of columns (m).

$ n \equiv m $

Below is an example of an order 3 square matrix.

$\begin{aligned}
M = \begin{pmatrix} 1\; 2\; 3\\
1\; 2\; 3\\
1\; 2\; 3
\end{pmatrix}
\end{aligned}
$

Square matrices are readily added and multiplied together and are the basis of many simple linear transformations, such as rotations (as in the rotations of images).

## Symmetric Matrix

A symmetric matrix is a type of square matrix where the top-right triangle is the same as the bottom-left triangle.

To be symmetric, the axis of symmetry is always the main diagonal of the matrix, from the top left to the bottom right. Below is an example of a 5 x 5 symmetric matrix.

$\begin{aligned}
M = \begin{pmatrix}
1\; 2\; 3\; 4\; 5\\
2\; 1\; 2\; 3\; 4\\
3\; 2\; 1\; 2\; 3\\
4\; 3\; 2\; 1\; 2\\
5\; 4\; 3\; 2\; 1\\
\end{pmatrix}
\end{aligned}
$

A symmetric matrix is always square and equal to its own transpose. The transpose is an operation that flips the number of rows and columns.

$ M = M^T $

## Triangular Matrix

A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values. A triangular matrix with values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular matrix with values only below the main diagonal is called a lower triangular matrix. 

Below is an example of a 3 x 3 upper triangular matrix.

$\begin{aligned}
M = \begin{pmatrix}
1\; 2\; 3\\
0\; 2\; 3\\
0\; 0\; 3\\
\end{pmatrix}
\end{aligned}
$

Below is an example of a 3 x 3 lower triangular matrix

$\begin{aligned}
M = \begin{pmatrix}
1\; 0\; 0\\
1\; 2\; 0\\
1\; 2\; 3\\
\end{pmatrix}
\end{aligned}
$

NumPy provides functions to calculate a triangular matrix from an existing square matrix. The **tril()** function to calculate the lower triangular matrix from a given matrix and the **triu()** to calculate the upper triangular matrix from a given matrix The example below defines a 3 x 3 square matrix and calculates the lower and upper triangular matrix from it.

In [1]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)

# lower triangular matrix
lower = tril(M)
print(lower)

# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


## Diagonal Matrix

A diagonal matrix is one where values outside of the main diagonal have a zero value, where the main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix is often denoted with the variable D and may be represented as a full matrix or as a vector of values on the main diagonal.

Below is an example of a 3 x 3 square diagonal matrix.

$\begin{aligned}
D = \begin{pmatrix}
1\; 0\; 0\\
0\; 2\; 0\\
0\; 0\; 3
\end{pmatrix}
\end{aligned}
$

As a vector, it would be represented as:

$\begin{aligned}
D = \begin{pmatrix}
d_{1,1}\\
d_{2,2}\\
d_{3,3}
\end{pmatrix}
\end{aligned}
$

A diagonal matrix does not have to be square. In the case of a rectangular matrix, the diagonal would cover the dimension with the smallest length; for example:

$\begin{aligned}
D = \begin{pmatrix}
1\; 0\; 0\; 0\\
0\; 2\; 0\; 0\\
0\; 0\; 3\; 0\\
0\; 0\; 0\; 4\\
0\; 0\; 0\; 0
\end{pmatrix}
\end{aligned}
$

NumPy provides the function **diag()** that can create a diagonal matrix from an existing matrix, or transform a vector into a diagonal matrix. The example below defines a 3 x 3 square matrix, extracts the main diagonal as a vector, and then creates a diagonal matrix from the extracted vector.

In [2]:
# diagonal matrix
from numpy import array
from numpy import diag

# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)

# extract diagonal vector
d = diag(M)
print(d)

# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


## Identity Matrix

An identity matrix is a square matrix that does not change a vector when multiplied. The values of an identity matrix are known. All of the scalar values along the main diagonal (top-left to bottom-right) have the value one, while all other values are zero.

An identity matrix is often represented using the notation I or with the dimensionality $I^n$, where n is a subscript that indicates the dimensionality of the square identity matrix. In some notations, the identity may be referred to as the unit matrix, or $U$, to honor the one value it contains (this is difierent from a Unitary matrix). For example, an identity matrix with the size 3 or $I^3$ would be as follows:

$\begin{aligned}
I = \begin{pmatrix}
1\; 0\; 0\\
0\; 1\; 0\\
0\; 0\; 1
\end{pmatrix}
\end{aligned}
$

In NumPy, an identity matrix can be created with a specific size using the **identity()** function. The example below creates an $I^3$ identity matrix.

In [3]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Alone, the identity matrix is not that interesting, although it is a component in other import matrix operations, such as matrix inversion.

## Orthogonal Matrix

Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1 then the vectors are called orthonormal because they are both orthogonal and normalized.

$v\; . \;w = 0$

or

$v\; . \;w^T = 0$

This is intuitive when we consider that one line is orthogonal with another if it is perpendicular to it. An orthogonal matrix is a type of square matrix whose columns and rows are orthonormal unit vectors, e.g. perpendicular and have a length or magnitude of 1.

An Orthogonal matrix is often denoted as uppercase Q. The Orthogonal matrix is dened formally as follows:

$Q^T\; . \;Q = Q\; . \;Q^T = I$

Where Q is the orthogonal matrix, $Q^T$ indicates the transpose of Q, and I is the identity matrix. A matrix is orthogonal if its transpose is equal to its inverse.

$Q^T = Q^{-1}$

Another equivalence for an orthogonal matrix is if the dot product of the matrix and itself equals the identity matrix.

$Q\; . \;Q^T = I$

Orthogonal matrices are used a lot for linear transformations, such as reflections and permutations. A simple 2 x 2 orthogonal matrix is listed below, which is an example of are reflection matrix or coordinate reflection.

$\begin{aligned}
Q = \begin{pmatrix}
1\; 0\\
0\; -1
\end{pmatrix}
\end{aligned}
$